export type EventItem = { step: number; kind: string; entityId: string; reasons: string[]; metrics: Record<string, number> };
export type Cell = { id: string; organism_id: string; energy: number; utility: number; activation: number; age_steps: number; redundancy: number };
export type Organism = { id: string; lineage: string; color: string; cellIds: string[]; energy: number; utility: number; contribution: number; colonyId: string | null; ageSteps: number; bornStep: number; wins: number; lastActiveStep: number; inactiveSteps: number; lifecycleState: 'young' | 'mature' | 'dormant'; protectedUntil: number; lowValueSteps: number; dormantSince: number | null; reactivations: number; foodEvidence: number; digestionEvidence: number; memoryIds: string[]; intermediateDimensions: number; microAffinities: Record<string, number>; microProfileUpdates: number; x: number; y: number; heading: number; distanceTravelled: number };
export type Colony = { id: string; member_ids: string[]; core_members: string[]; energy: number; state: string; formed_step: number; synergy: number };
export type MemoryEngram = { id: string; member_ids: string[]; created_step: number; last_recalled_step: number; recall_count: number; digestion_count: number; mean_error: number; stability: number; state: string };
export type RetinalStimulus = { id: string; rotation: number; scale: number; noise: number; occlusion: number; offsetX: number; offsetY: number; retinaSide: number; retinaPixels: number[]; renderMode: 'filled' | 'outline' };
export type MicroSignatureState = { id: string; bornStep: number; lastActiveStep: number; observations: number; digestionCount: number; foodEvidence: number; energy: number; colonyId: string | null };
export type MicroColonyState = { id: string; member_ids: string[]; formed_step: number; last_active_step: number; coactivations: number; stability: number };
export type InformationPatch = { id: string; x: number; y: number; amount: number; novelty: number; createdStep: number; consumedBy: string | null; digested?: boolean; memoryId?: string | null; microFood?: number; microActivations?: string[] };
export type State = {
  seed: number;
  stepCount: number;
  stateHash: string;
  currentStimulus: RetinalStimulus | null;
  metrics: { loss: number; meanLoss: number; activeCells: number; residentCells: number; activeOrganisms: number; residentOrganisms: number; dormantOrganisms: number; consolidatedMemories: number; digestedSamples: number; totalInformationFood: number; microSignatures: number; microColonies: number; currentMicroFood: number; microDigestedDetails: number; activeColonies: number; activeSynapsesProxy: number; memoryBytesProxy: number; resourceScore: number; events: number };
  cells: Cell[];
  organisms: Organism[];
  colonies: Colony[];
  memories: MemoryEngram[];
  microSignatures: MicroSignatureState[];
  microColonies: MicroColonyState[];
  informationPatches: InformationPatch[];
  events: EventItem[];
};
export type Evaluation = { modelModified: boolean; sampleCount: number; purity: number; communities: { organismId: string; dominantHiddenLabel: string; samples: number }[]; note: string };
export type Ablation = { organismId: string; modelModified: boolean; baselineLoss: number; ablatedLoss: number; delta: number; note: string };
export type DrawingAudit = {
  auditId: string;
  modelModified: boolean;
  stateHashBefore: string;
  stateHashAfter: string;
  retinaSide: number;
  normalizedPixels: number[];
  ecosystemResponse: { organismId: string | null; colonyId: string | null; confidence: number; reconstructionError: number | null };
  externalAuditor: { drawnLabel: string; confidence: number; geometricMatch: number; labelScores: Record<string, number>; organismAssociatedLabel: string; mappingSupport: number };
  agreement: boolean;
  note: string;
};
export type ResearchAudit = {
  schema: string;
  auditId: string | null;
  generatedAt: string;
  provider: 'OpenAI';
  model: string;
  requestedModel: string;
  snapshotStateHash: string;
  cached: boolean;
  modelModified: false;
  learningWriteAccess: false;
  rawRetinaShared: false;
  boundaryNote: string;
  usage: { inputTokens?: number; outputTokens?: number; totalTokens?: number } | null;
  snapshotExtractionHashBefore: string;
  snapshotExtractionHashAfter: string;
  liveStateHashAtResponse: string;
  liveStateAdvancedDuringAudit: boolean;
  analysis: {
    headline: string;
    verdict: 'insufficient data' | 'promising but preliminary' | 'stable on current benchmark' | 'needs attention';
    judgeTakeaway: string;
    executiveSummary: string;
    findings: { title: string; observation: string; evidence: string[]; interpretation: string }[];
    risks: { severity: 'low' | 'medium' | 'high'; issue: string; whyItMatters: string }[];
    nextExperiments: { priority: 'now' | 'next' | 'later'; title: string; hypothesis: string; protocol: string; successMetric: string }[];
    publicationReadiness: { stage: 'insufficient evidence' | 'proof of concept' | 'workshop ready' | 'paper candidate'; strongestEvidence: string; missingEvidence: string };
    resourceAssessment: { status: 'proxy only' | 'partially measured' | 'measured'; interpretation: string };
  };
};
